server.port=8080
spring.application.name=rag
# CORS Configuration
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=*
spring.mvc.cors.allowed-headers=*

# Optional: Disable multipart limit so user can upload big PDFs if needed
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
